---
app: wordpress-mysql-update-2
auto_deploy: true
context: release-w9nh6s
domain: your-company-name.xyz
repo_name: dustyspace/wordpress-mysql
hostnames:
- wordpress: wordpress-wordpress-mysql-update-2-${env_id}.${domain}
environment_templates:
- name: ephemeral
- name: permanent
resources:
  cpu:
    limits: 1000m
    requests: 100m
  memory:
    limits: 1Gi
    requests: 100Mi
  replicas: 1
services:
- name: db
  image: mysql:8.0.19
  has_repo: false
  volumes:
  - name: db_data
    type: persistent
    mount_path: "/var/lib/mysql"
  args:
  - "--default-authentication-plugin=mysql_native_password"
  storage:
    size: 10Gi
    type: aws-efs
- name: wordpress
  image: wordpress:latest
  has_repo: false
  ports:
  - type: node_port
    target_port: '80'
    port: '80'
    loadbalancer: false
workflows:
- name: setup
  parallelize:
  - step: services
    tasks:
    - services.db
    - services.wordpress
- name: patch
  parallelize:
  - step: services
    tasks:
    - services.db
    - services.wordpress
- name: teardown
  parallelize:
  - step: remove_environment
    tasks:
    - release.remove_environment
