---
defaults: []
services:
  db:
  - key: MYSQL_ROOT_PASSWORD
    secret: true
  - key: MYSQL_DATABASE
    value: wordpress
  - key: MYSQL_USER
    value: wordpress
  - key: MYSQL_PASSWORD
    secret: true
  wordpress:
  - key: WORDPRESS_DB_HOST
    value: db
  - key: WORDPRESS_DB_USER
    value: wordpress
  - key: WORDPRESS_DB_PASSWORD
    secret: true
  - key: WORDPRESS_DB_NAME
    value: wordpress
